version: '3.4'

services:
    sql:
        build: ./SQL/
        container_name: sql_rafiki
        ports: 
            - "127.0.0.1:41433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=password
        volumes:
            - dbdata:/var/opt/mssql
    
    elastic: 
        build: ./Elastic/
        container_name: elastic_rafiki
        ports: 
            - "127.0.0.1:49200:9200"
            - "127.0.0.1:49300:9300"
        environment:
            - START_DAEMON=true
        volumes:
            - elasticdata:/usr/share/elasticsearch/data
            - ./Elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

    kibana:
        build: ./Kibana/
        container_name: kibana_rafiki
        depends_on:
            - elastic
        ports: 
            - "127.0.0.1:45601:5601"
        environment:
            - ELASTICSEARCH_URL=http://elastic:9200
        volumes: 
            - ./Kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

    redis:
        build: ./Redis/
        container_name: redis_rafiki
        ports:
            - "127.0.0.1:46379:6379"

volumes: 
    dbdata:
    elasticdata:
